---

- name: prepare post-hook options
  set_fact:
    post_hook: "--post-hook 'systemctl restart {{ cert.services|join(' ') }}'"
  when: cert.services|d()

- name: register Let's Encrypt certificate with HTTP challenge
  command: >
    certbot certonly --apache
    --domains {{ cert.domains|join(',') }}
    --preferred-challenge=http
    --keep-until-expiring --expand
    --quiet --non-interactive --agree-tos
    {{ post_hook|d() }}
  when: cert.challenge|d() == 'http' and cert.domains|d()

- name: register Let's Encrypt certificate with DNS challenge
  command: >
    certbot certonly --manual
    --domains {{ cert.domains|join(',') }}
    --preferred-challenge=dns
    --keep-until-expiring --expand
    --quiet --non-interactive --agree-tos
    --manual-public-ip-logging-ok
    --manual-auth-hook 'certbot-dns-hook.sh auth'
    --manual-cleanup-hook 'certbot-dns-hook.sh cleanup'
    {{ post_hook|d() }}
  when: cert.challenge|d() == 'dns' and cert.domains|d()

- name: register system users
  command: "cut -d: -f1 /etc/passwd"
  register: le_reg_system_users

- name: add users to letsencrypt system group
  user:
    name: "{{ item }}"
    groups: letsencrypt
    append: yes
  with_items: "{{ cert.users|d([]) }}"
  when: cert.users|d() and item in le_reg_system_users.stdout_lines|d([])
